### ISSUE TITLE
Allow the ability to edit goals and milestones on the goals page itself

### ISSUE THREAD

**Issue by BigBrad12** [BigBrad12/proj-app#19]
- [x] edit goal title
- [x] edit milestone title

- [x] edit goal target date
  - [x] change the span to an input
  - [x] fix the adding new goal element logic to add an input element, not a span for the target date
  - [x] make the element a date pickr instance
  - [x] fix the styling of the input element
  - [x] probably add event listeners for the blur and then update to back end
  - [x] add logic for updating the days left value when a new target date is selected
  - [x] add logic for changing the status when the goal date is changed

- [x] edit milestone target date
  - [x] change the span to an input element
  - [x] make element date pickr instance
  - [x] fix styling
  - [x] fix add new milestone element logic
  - [x] set up event listeners and logic for blur element etc
  - [x] add logic to re-order the milestone element based on the new date
  - [x] use one blur element event listener and pass a param in to define which type

**Comment by BigBrad12** [comment]
- [ ] edit milestones on the page itself
